### PR TITLE
SSR support

### LINKED ISSUE #2: support server-side rendering
We need to [avoid accessing DOM globals like `document`](https://github.com/discord/focus-rings/blob/main/src/FocusRingContext.tsx#L171) without checking if they exist.

### PR DESCRIPTION
**Pull request by Dev-CasperTheGhost**
## This PR adds

- Server side rendering support

**This has been tested with `next.js@^10.1.2` and `react@17.0.2`**

Closes #2

### CODE REVIEW

**Comment by Dev-CasperTheGhost** [comment]
Any news on this @aweary? sorry for ping 😅

**Comment by IanMitchell** [comment]
Thanks for the PR! Brandon is on vacation right now, it might be a bit before he's able to review it 😄

**Comment by Dev-CasperTheGhost** [comment]
> Thanks for the PR! Brandon is on vacation right now, it might be a bit before he's able to review it 😄

No worries! Thanks for your response 😄

**Comment by kylegoines** [comment]
very much interested in this feature 📦

**Comment by Dev-CasperTheGhost** [comment]
Any news on this? I'd like to add it to my project 😅

**Comment by Dev-CasperTheGhost** [comment]
> Sorry this took so long to get in! Merging and I'll get a new release up soon!

No worries. Thanks!

**Pull request merged**
